### ISSUE TITLE
Meters readings are not saved (pt 2.b from task description)

### ISSUE THREAD

**Issue by LevchenCoM** [seruygrid/WebRiders#2]
Hi @seruygrid, at now you use uploaded readings only for built chart and they are not saved persistently in the DB.
Could you implement the logic that will save the readings to the DB and use them to build the chart on the meters page without reuploading .csv file?

Please, tell me if you have any questions.
Thanks.

**Comment by seruygrid** [comment]
Hi @LevchenCoM, I fixed all the bugs.
